### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Domosed-gamin** [bastibl/bame#1]
Great implementation of old good flash game. Speed is very fast for me. Please add easy mode for nabs like me. Also please add license file. Thank you for shared source. You are cool, man.

**Comment by bastibl** [comment]
Thanks for you feedback. Really made my day to get a  positive comment on the first code I pushed online :-) I just added MIT license and made the game start slower (2.5 secs per line in level 1).

You can modify `INIT_DELAY` to your needs: https://github.com/bastibl/bame/blob/master/bame.c#L14

**Comment by Domosed-gamin** [comment]
Cool. Thank you!
